<?xml version="1.0"?>
<package format="3">
  <name>smart_energy_management_robot</name>
  <version>0.0.1</version>
  <description>Smart Energy Management Robot - EE650</description>
  <maintainer email="jiayi.zhang.2026@mumail.ie">jiayi_zhang</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>nav2_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>plansys2_msgs</depend>
  <depend>plansys2_executor</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
